### ISSUE TITLE
大神，求问下 vue-cli3中这个怎么配置

### ISSUE THREAD

**Issue by ngcly** [biguokang/live2d_ai#1]
在vue-cli3种一直报 initModel is not defined ，js，cs,我都引入了。不知道为啥就是调用不了那个js的方法

**Comment by AlpacaBi** [comment]
你要把这个项目加载进webpack打包么，那工程量有点大。我还在研究如何加进webpack里

发自毕国康的 iPhone

在 2018年12月5日，下午5:54，宁哥CLY <notifications@github.com<mailto:notifications@github.com>> 写道：


在vue-cli3种一直报 initModel is not defined ，js，cs,我都引入了。不知道为啥就是调用不了那个js的方法

**Comment by ngcly** [comment]
好吧，我也是刚学vue的半吊子，后台写过各种html，但是碰到单页面就一脸懵了。所以就用了最新的vue-cli3脚手架搭的，看了你这个动漫小人物挺好玩 想加载进去，一直加不进去，好尴尬。

**Comment by AlpacaBi** [comment]
你可以直接嵌入在index.html里面的，我也是部署在单页应用里

发自毕国康的 iPhone

在 2018年12月6日，上午9:27，宁哥CLY <notifications@github.com<mailto:notifications@github.com>> 写道：


好吧，我也是刚学vue的半吊子，后台写过各种html，但是碰到单页面就一脸懵了。所以就用了最新的vue-cli3脚手架搭的，看了你这个动漫小人物挺好玩 想加载进去，一直加不进去，好尴尬。

**Comment by ngcly** [comment]
好的，谢谢大神
